spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://47.98.128.180:3306/count_votes?useUnicode=true&characterEncoding=utf-8
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root123456
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true

