spring:
  datasource:
    hikari:
      maximum-pool-size: 15
      max-lifetime: 180000
      idle-timeout: 60000
      connection-timeout: 20000
      minimum-idle: 5
    url: jdbc:mysql://47.98.128.180:3306/xunwu?useUnicode=true&characterEncoding=utf-8
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root0808
  thymeleaf:
    cache: false

  servlet:
    multipart:
      enabled: true
      location: E:\IdeaWorkSpace\xunwu\temp
      max-request-size: 20MB
      file-size-threshold: 5MB


# 七牛
qiniu:
  accessKey: oWVDkEnTv7i8PdpbmPRXaKa8AfacwtjMu82407EW
  secretKey: HIkO75z-LXLKRIUe0RpHfHzSuaDHJ_fI5RQbR7Hn
  bucket: cpfxunwu
  cdn:
    prefix: http://zips.lmcpf.com/